const VA = {
  HF_REPO: "invi-bhagyesh/ValueArena",
  HF_BASE: "https://huggingface.co/datasets/invi-bhagyesh/ValueArena/resolve/main",
  GIT_REPO: "https://github.com/jchang153/EigenBench",
  OPENROUTER_BASE: "https://openrouter.ai/api/v1",
  CHAT_MODELS: [
    { id: "anthropic/claude-sonnet-4", label: "Claude 4 Sonnet" },
    { id: "openai/gpt-4.1", label: "GPT 4.1" },
    { id: "openai/gpt-4.1-mini", label: "GPT 4.1 Mini" },
    { id: "google/gemini-2.5-flash", label: "Gemini 2.5 Flash" },
    { id: "google/gemini-2.5-pro", label: "Gemini 2.5 Pro" },
    { id: "meta-llama/llama-4-maverick", label: "Llama 4 Maverick" },
    { id: "meta-llama/llama-4-scout", label: "Llama 4 Scout" },
    { id: "deepseek/deepseek-r1", label: "DeepSeek R1" },
    { id: "qwen/qwen3-235b-a22b", label: "Qwen3 235B" },
  ],
  CONSTITUTIONS: [
    { id: "kindness", label: "Kindness" },
    { id: "goodness", label: "Goodness" },
    { id: "humor", label: "Humor" },
    { id: "sarcasm", label: "Sarcasm" },
    { id: "loving", label: "Loving" },
    { id: "poeticism", label: "Poeticism" },
    { id: "nonchalance", label: "Nonchalance" },
    { id: "remorse", label: "Remorse" },
    { id: "impulsiveness", label: "Impulsiveness" },
    { id: "mathematical", label: "Mathematical" },
    { id: "sycophancy", label: "Sycophancy" },
    { id: "misalignment", label: "Misalignment" },
    { id: "claude", label: "Claude" },
    { id: "openai", label: "OpenAI" },
    { id: "conservatism", label: "Conservatism" },
    { id: "deep_ecology", label: "Deep Ecology" },
  ],
};
